### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by msyyc**
# Cadl Ranch Contribution Checklist:

- [ ] I have written a [scenario spec](../docs/writing-scenario-spec.md)
- [ ] I have **meaningful** `@scenario` names. Someone can look at the list of scenarios and understand what I'm covering.
- [ ] I have written a [mock API](../docs/writing-mock-apis.md)
- [ ] I have used `@scenarioDoc`s for extra scenario description and to tell people **how to pass** my mock api check.

### CODE REVIEW

**Comment by msyyc** [comment]
release new version after bumping tsp version: https://github.com/Azure/cadl-ranch/pull/399

**Review by timotheeguerin — APPROVED** [review]

**Comment by msyyc** [comment]
It seems release fails: https://github.com/Azure/cadl-ranch/actions/runs/5804471290/job/15734081602 @timotheeguerin

**Comment by msyyc** [comment]
I rerun the pipeline and it succeeds now: https://www.npmjs.com/search?q=%40azure-tools%2Fcadl-ranch

**Comment by timotheeguerin** [comment]
That pipeline just create the auto release branch and i think there is a bug where it crash right after merging it because there is no changes. Just ignore it. The actual release pipeline is in the internal devops

**Pull request merged**
