### PR TITLE
Use (more of) unambiguous float32 values

### PR DESCRIPTION
**Pull request by antkmsft**
The same reason as for #516.

### CODE REVIEW

**Comment by antkmsft** [comment]
CI is failing, how can I fix that? It does not seem closely related to the changes that I made.
```
error: ✘ Deprecated: version: property is deprecated in @service. If wanting to describe a service versioning you can use the `@typespec/versioning` library. If wanting to describe the project version you can use the package.json version.: /home/runner/work/cadl-ranch/cadl-ranch/packages/cadl-ranch-specs/http/client/structure/common/service.tsp:32:3
error: ✘ ✘ Scenario client/structure/two-operation-group is invalid.
debug: Found scenario "/home/runner/work/cadl-ranch/cadl-ranch/packages/cadl-ranch-specs/http/client/structure/renamed-operation/client.tsp"
error: ✘ Deprecated: version: property is deprecated in @service. If wanting to describe a service versioning you can use the `@typespec/versioning` library. If wanting to describe the project version you can use the package.json version.: /home/runner/work/cadl-ranch/cadl-ranch/packages/cadl-ranch-specs/http/client/structure/common/service.tsp:32:3
error: ✘ ✘ Scenario client/structure/renamed-operation is invalid.
debug: Found scenario "/home/runner/work/cadl-ranch/cadl-ranch/packages/cadl-ranch-specs/http/client/structure/multi-client/client.tsp"
error: ✘ Deprecated: version: property is deprecated in @service. If wanting to describe a service versioning you can use the `@typespec/versioning` library. If wanting to describe the project version you can use the package.json version.: /home/runner/work/cadl-ranch/cadl-ranch/packages/cadl-ranch-specs/http/client/structure/common/service.tsp:32:3
error: ✘ ✘ Scenario client/structure/multi-client is invalid.
debug: Found scenario "/home/runner/work/cadl-ranch/cadl-ranch/packages/cadl-ranch-specs/http/client/structure/default/client.tsp"
error: ✘ Deprecated: version: property is deprecated in @service. If wanting to describe a service versioning you can use the `@typespec/versioning` library. If wanting to describe the project version you can use the package.json version.: /home/runner/work/cadl-ranch/cadl-ranch/packages/cadl-ranch-specs/http/client/structure/common/service.tsp:32:3
```

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
I think the cause is this
https://github.com/Azure/cadl-ranch/blob/7886a78b50ff297f9a1d3cb814152c231f17e5bb/packages/cadl-ranch-specs/http/client/structure/common/service.tsp#L32

May need to change to this `@versioned` + a `Versions` (name not matter) enum.
https://github.com/Azure/cadl-ranch/blob/7886a78b50ff297f9a1d3cb814152c231f17e5bb/packages/cadl-ranch-specs/http/resiliency/srv-driven/main.tsp#L10

@qiaozha for comment

**Comment by timotheeguerin** [comment]
Yeah this is just a test checking against latest dev version I need to update the specs. And no let's just remove the version property that should not be used, let's not use versioning everywhere and complexity every spec

**Comment by qiaozha** [comment]
should we remove `@service.version` after the new typespec is released or should we fix it now ?

**Review by qiaozha — APPROVED** [review]

**Comment by timotheeguerin** [comment]
> should we remove `@service.version` after the new typespec is released or should we fix it now ?

we can do it now, removing here https://github.com/Azure/cadl-ranch/pull/528

**Review by timotheeguerin — APPROVED** [review]

**Comment by antkmsft** [comment]
Thanks!

**Pull request merged**
